### ISSUE TITLE
missing user

### ISSUE THREAD

**Issue by shorif2000** [whittlem/aws-ec2-install-scripts#2]
you don't have `adduser wwwrun`

**Comment by whittlem** [comment]
aws-ec2-install-scripts/aws-ec2-rhel8-common-runfirst.sh <-- "run first" :)

mkdir -p /opt/SP/home
groupadd www
useradd -c "WWW Run User" -d /opt/SP/home/wwwrun -s /sbin/nologin -g www wwwrun
usermod -a -g www wwwrun
